### ISSUE TITLE
Use buffers instead of parameters in the Downsample layer

### ISSUE THREAD

**Issue by Skydes** [adobe/antialiased-cnns#1]
Thank you for sharing this great work and for open-sourcing your code!

I think that the [things to watch out for](https://github.com/adobe/antialiased-cnns#some-things-to-watch-out-for) could be avoided by defining the weights in the Downsample layer as buffers instead of parameters. See [`torch.nn.Module.register_buffer`](https://pytorch.org/docs/stable/nn.html#torch.nn.Module.register_buffer).

**Comment by richzhang** [comment]
Thanks a lot for the suggestion! I integrated the change. `Downsample` now has buffer `self.filt` and calls function `F.conv2d` at the forward pass.

The `nn.Conv2d` is still there for legacy reasons -- optimizer.load_state_dict( ) doesn't play well if I remove it -- but the layer is not used at all, and it adds minimal memory to the saved files.

**Comment by Skydes** [comment]
Looks good, thanks for having addressed that!
