### ISSUE TITLE
Adaptive version?

### ISSUE THREAD

**Issue by Vlad0922** [adobe/antialiased-cnns#12]
Hi folks,

A lot of implementations use adaptive versions of poolings to support images with different resolutions (e.g. most of the models from [this repo](https://github.com/Cadene/pretrained-models.pytorch) use it).

Is it possible to modify downsampling layer to support adaptive behaviour?

**Comment by richzhang** [comment]
Not sure what you mean exactly. But if you want to replace a `stride=4` layer, rather than `stride=2`, which we experimented with, yes, a wider blur kernel can be used.

**Comment by rsomani95** [comment]
@Vlad0922 I think Adaptive pooling layers are typically used on the final convolutional feature map, before being fed into the hidden layer. Are those the layers you were referring to? (Though in [this](url) implementation of MobileNet-V3, they use adaptive pooling inside the inverted residual blocks)

@richzhang's Adaptive pooling takes as input only the output size and internally adjusts the kernel size to produce the desired output size ([docs](https://pytorch.org/docs/stable/generated/torch.nn.AdaptiveAvgPool2d.html)). I think an adaptive BlurPool version would require computing the `filter_size` on the fly?

On a related note, would you recommend adding a BlurPool layer for the final feature map downsampling?
