### ISSUE TITLE
Unable to establish SSL connection,when use command: bash weights/download_antialiased_models.sh

### ISSUE THREAD

**Issue by LuZeking** [adobe/antialiased-cnns#16]
![image](https://user-images.githubusercontent.com/35646334/62849065-b8427400-bd10-11e9-84c8-044aa1e98edb.png)

**Comment by richzhang** [comment]
Were you able to download the model? Thanks.

**Comment by doublemanyu** [comment]
Hi, I downloaded the model, but it can not be decompressed. Can you share the model? Thank you in advance.

**Comment by richzhang** [comment]
The model is not supposed to be decompressed. It can be loaded, as shown in the code.
