### ISSUE TITLE
Implementation of original ResNet

### ISSUE THREAD

**Issue by jimmy15923** [adobe/antialiased-cnns#18]
Hi!
I am confused about the code In the L170-171 of [resnet.py](https://github.com/adobe/antialiased-cnns/blob/master/models_lpf/resnet.py#L170-L171).
In the [original implementation of resnet](https://github.com/pytorch/vision/blob/master/torchvision/models/resnet.py#L143), It should be max-pooling 2D, which is 
```python
nn.MaxPool2d(kernel_size=2, stride=2)
```
Why do you use nn.MaxPool2d(kernel_size=2, stride=1) and  Downsample layer (with Gaussian blur) instead?

**Comment by richzhang** [comment]
This is the main proposal in the paper -- please see Figs 2 and 3. Doing so better follows signal processing principles and improves the robustness to shifts.
