### ISSUE TITLE
Asking for Anti-antialiased U-Net codes

### ISSUE THREAD

**Issue by zhangfb** [adobe/antialiased-cnns#21]
Hi, could you provide the **anti-antialiased U-Net** codes which you used in pix2pix? I wonder how you apply **blurring after upsampling**. Thank you in advance!

**Comment by iperov** [comment]
I just replaced MaxPooling2D() within BlurPool(filt_size=3) in my UNet segmentation network.

drawback is error now has a kicks during the training
![firefox_2019-09-05_08-07-55](https://user-images.githubusercontent.com/8076202/64311206-45958300-cfb4-11e9-941c-9cf73d35dcf9.jpg)

**Comment by mrgloom** [comment]
Some related info https://github.com/adobe/antialiased-cnns/issues/8
