### ISSUE TITLE
No strided pooling

### ISSUE THREAD

**Issue by a462428** [adobe/antialiased-cnns#22]
Hi, as the theory, strided downsample layer should be revised, and I wonder that pooling with size=3, stride=1 should be replaced as your version?
Thx!

**Comment by richzhang** [comment]
If there's no striding, the no need to do antialiasing (at least for downsampling purposes).

**Comment by a462428** [comment]
Thx!
Another question,  maxpool with “ceil_mode=True” and stride=2 kernel=2 will be wrong! 
Error: cudnnconvolutionbackward is at version 1 expected version
