### ISSUE TITLE
can i cite the figure of the paper directly?

### ISSUE THREAD

**Issue by yelusaleng** [adobe/antialiased-cnns#24]
hi, author,
i want to cite your figure 4 in my paper. 
however, i can't find the information about right/permission.
can i cite your figure if i give clear indication in my paper?
expecting your answer, many thanks!

**Comment by yelusaleng** [comment]
and figure3 ...

**Comment by richzhang** [comment]
Yes, no problem. Just indicate where it came from in the caption.
