### ISSUE TITLE
Is AvrPool already an antialiased downsampling method? 

### ISSUE THREAD

**Issue by mrgloom** [adobe/antialiased-cnns#26]
I wonder is AvrPool already an antialiased downsample? and it's just a special case - filter size 2?

https://github.com/adobe/antialiased-cnns/blob/3f3f96074014952887500614df9f0d00732adb11/models_lpf/__init__.py#L29

**Comment by richzhang** [comment]
Yes, you are right. It is also mentioned on page 5 of the [paper](https://arxiv.org/pdf/1904.11486.pdf).

Thanks!
