### ISSUE TITLE
Smooth convolutional filters instead of feature maps?

### ISSUE THREAD

**Issue by mrgloom** [adobe/antialiased-cnns#27]
From the paper:
> How do the learned convolutional filters change? Our proposed change smooths the internal feature maps for purposes of downsampling. How does training with this layer affect the learned convolutional layers? ... the anti-aliased networks (red-purple) actually learn smoother filters throughout the network, relative to the baseline (black). Adding in more aggressive low-pass filtering further decreases the TV (increasing smoothness). This indicates that our method actually induces a smoother feature extractor overall.

I wonder is it possible to smooth convolutional filters itself instead of feature maps?

**Comment by richzhang** [comment]
While that would help, it would not be antialiasing the exact signal that is to be downsampled, since there are subsequent nonlinearities, such as relus and maxpool.
