### ISSUE TITLE
Why Conv->Relu->BlurPool ?

### ISSUE THREAD

**Issue by mrgloom** [adobe/antialiased-cnns#29]
Why Conv->Relu->BlurPool and not Conv->BlurPool->Relu?

Just as a sidenote for maxpooling there is no difference https://stackoverflow.com/questions/35543428/activation-function-after-pooling-layer-or-convolutional-layer

**Comment by richzhang** [comment]
Conv->BlurPool->Relu is equivalent to Blur(stride1)-Conv(stride2)-Relu. In essense, this is blurring the input signal and destroy information before the "feature extraction" layers of Conv-Relu
