### ISSUE TITLE
Utility for own model require a retrained Imagenet Pretrained ? 

### ISSUE THREAD

**Issue by JarveeLee** [adobe/antialiased-cnns#3]
Thanks for your great work. 
Models applied in other task usually require a Imagenet Pretrained backbones. 
If I want to  use this Module into own backbone , is it necessary to train a ImageNet Pretrain ... ?
Or just replace MaxPool with MaxBlurPool then load the original Pretrain weight, then to train other task ? 
For example you don't have Res101 in weights/download_antialiased_models.sh , but I hope to farely compare Res101 with the same Pretrained weights.

**Comment by richzhang** [comment]
Yes -- models should be retrained (or fine-tuned) after adding the antialiasing layers. I just added antialiased ResNet101 models.

**Comment by JarveeLee** [comment]
Thanks~

**Comment by richzhang** [comment]
I added instructions for loading an antialiased model (simple 2 lines of code!). I think this covers it, so I'm closing this issue now. Thanks for your interest in the project!

**Comment by dongzhi0312** [comment]
> Thanks for your great work.
> Models applied in other task usually require a Imagenet Pretrained backbones.
> If I want to use this Module into own backbone , is it necessary to train a ImageNet Pretrain ... ?
> Or just replace MaxPool with MaxBlurPool then load the original Pretrain weight, then to train other task ?
> For example you don't have Res101 in weights/download_antialiased_models.sh , but I hope to farely compare Res101 with the same Pretrained weights.

can you share the weights of author offered? I cannot download, thanks

**Comment by richzhang** [comment]
They should be listed in [this file](https://github.com/adobe/antialiased-cnns/blob/master/weights/download_antialiased_models.sh). Thanks!
