### ISSUE TITLE
RuntimeError when training resnext50_32x4d

### ISSUE THREAD

**Issue by NightQing** [adobe/antialiased-cnns#33]
Hi, 
I have trained a resnet50 model successfully, but when I train resnext50_32x4d, there is an error:
models_lpf/resnet.py", line 147, in forward
    out += identity
RuntimeError: The size of tensor a (20) must match the size of tensor b (80) at non-singleton dimension 3.

In addition, in models_lpf/resnet.py, "groups=4, width_per_group=32" in resnext32x4d is differenet from "groups=32, width_per_group=4" in pytorch offical code "torchvision/models/resnet.py"
Do you have any advices?

**Comment by honglu-intel** [comment]
just run into the exact sample problem, any update?

I tried switching the group and width_pre_group parameters. It messed up the network dimension even further. So that is not the solution.

**Comment by honglu-intel** [comment]
Just saw this issue is closed. Any updates? Thx much.
