### ISSUE TITLE
weights connot download can you offer other links,thanks

### ISSUE THREAD

**Issue by dongzhi0312** [adobe/antialiased-cnns#4]

**Comment by richzhang** [comment]
Can you check if your are updated in [this file](https://github.com/adobe/antialiased-cnns/blob/master/weights/download_antialiased_models.sh)? I recently made a small change. Thanks!

**Comment by dongzhi0312** [comment]
![image](https://user-images.githubusercontent.com/38675877/58770282-beb1c280-85e0-11e9-8971-1b788e037a60.png

**Comment by richzhang** [comment]
Hmm, I'll look into alternative methods for hosting.

**Comment by richzhang** [comment]
@dongzhi0312 Turns out Google Cloud services had some issues today, which may be the cause of the Dropbox issue. Could you try again?

**Comment by dongzhi0312** [comment]
thanks for your reply, I will try again, but it may be my network issues

**Comment by zxb-caffe** [comment]
Can you provide me a copy? The dropbox is blocked and I cannot log in.
