### ISSUE TITLE
Padding size issue for small images

### ISSUE THREAD

**Issue by DuyguSerbes** [adobe/antialiased-cnns#47]
Hello all,

I would like to train the model with CIFAR10.

But it gives error with blurring kernel size larger than 3:

RuntimeError: Padding size should be less than the corresponding input dimension, but got: padding (2, 2) at dimension 3 of input [64, 512, 2, 2]

What do you suggest? Is there a way to apply blurpool for small images?

**Comment by maniatisni** [comment]
I'm getting something similar. 

(I'm trying to anti-alias this [UNet](https://github.com/maniatisni/DAS-Denoising/blob/main/model.py), any help, welcome).

**Comment by richzhang** [comment]
Thanks for trying this. When the spatial map is so small (2x2), there is unlikely to be much benefit in using a large antialias kernel
