### ISSUE TITLE
About kernel_size of initial max pooing for Resnet

### ISSUE THREAD

**Issue by sweaterr** [adobe/antialiased-cnns#5]
Thank you for sharing this repo.

I remember that kernel_size of initial max pooing for original ResNet is 3.

Why did you change the kernel_size of initial max pooing for ResNet from 3 to 2?

https://github.com/adobe/antialiased-cnns/blob/master/models_lpf/resnet.py#L170

Is there a special reason?

**Comment by richzhang** [comment]
Thank you for finding this -- that was a mistake. I shouldn't have changed that. I will look into re-evaluating, although I doubt results will change much.

**Comment by sweaterr** [comment]
@richzhang Thanks for fast reply!.

**Comment by sweaterr** [comment]
@richzhang I have one more question 

I remember that stridedConv for original ResNet is 3x3 conv in bottleneck block.

But you moved stridedConv to final 1x1 conv in bottleneck block.

https://github.com/adobe/antialiased-cnns/blob/master/models_lpf/resnet.py#L117

Is there a special reason for this?

**Comment by richzhang** [comment]
Yes, that's the algorithm -- Conv(stride2)+Relu --> Conv(stride1)+Relu+Downsample(stride2). I lumped the Downsample with the next conv layer so that that the `forward` function wouldn't have to be changed.

**Comment by sweaterr** [comment]
@richzhang I understand it! it is reasonable. thank you for reply. 😄
