### ISSUE TITLE
FLOPS increase? 

### ISSUE THREAD

**Issue by bonlime** [adobe/antialiased-cnns#9]
Hi. Have you measured how does BlurPool affect the total number of multiply-adds needed for the model? I suppose it would make them a little bit more computationally heavy and wonder how huge is the increase.

**Comment by richzhang** [comment]
Thanks for the question.

Here's a timing plot. I measure the forward pass time for a batch of 48 on a GTX 2080 for ResNets 18-101. I plot accuracy vs runtime (left) and consistency vs runtime (right). Even if you only care about accuracy, the increased runtime pays for itself. For shift-invariance/consistency, it more than pays for itself.

![timing](https://user-images.githubusercontent.com/18079594/62168468-8249cc80-b2da-11e9-9f9f-86a9ff7f4f8a.jpg)

**Comment by bonlime** [comment]
@richzhang Thanks for the plots!
